export const ProductActionTypes = {
    PRODUCTS_SEARCH_INIT: 'PRODUCTS_SEARCH_INIT',
    PRODUCTS_SEARCH_SUCCESS: 'PRODUCTS_SEARCH_SUCCESS',
    PRODUCTS_SEARCH_FAILURE: 'PRODUCTS_SEARCH_FAILURE',

    PRODUCT_FETCH_INIT: 'PRODUCT_FETCH_INIT',
    PRODUCT_FETCH_SUCCESS: 'PRODUCT_FETCH_SUCCESS',
    PRODUCT_FETCH_FAILURE: 'PRODUCT_FETCH_FAILURE',
}